### ISSUE TITLE
wrapValue causing column not found error

### ISSUE THREAD

**Issue by jaysson** [bosnadev/database#37]
https://github.com/bosnadev/database/commit/910ecf3304b820586641e1901a4b69bd7396f63b has changed `PostgresGrammar.php` line 62 and 75. Due to this, `is null` queries (all queries in a model with soft delete) are throwing column not found error.

**Comment by gueroverde** [comment]
yes https://github.com/bosnadev/database/commit/910ecf3304b820586641e1901a4b69bd7396f63b#diff-3b456021f35683542752645028241c09L62

https://github.com/bosnadev/database/commit/910ecf3304b820586641e1901a4b69bd7396f63b#diff-3b456021f35683542752645028241c09L75

If the problem was caused when I changed this to pass the tests, I just noticed the error that caused that I see that pull request already exists thanks

**Comment by eatentree** [comment]
Any ETA?

**Comment by mirzap** [comment]
New version is tagged.
